### ISSUE TITLE
Running a Nikto v2.1.4 scan against IronBee results in occasional invalid free's in libhtp htp_tx_destroy

### ISSUE THREAD

**Issue by wmetcalf** [OISF/libhtp#19]
Running a Nikto v2.1.4 scan against IronBee results in occasional invalid free's in libhtp htp_tx_destroy.

./nikto.pl -update
./nikto.pl -host 127.0.0.1 -port 8080

```
Loaded symbols for /lib64/libgcc_s-4.4.5-20110214.so.1
Core was generated by `/usr/sbin/httpd'.
Program terminated with signal 6, Aborted.
#0  0x00007fb42260a945 in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
64    return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
(gdb) bt full
#0  0x00007fb42260a945 in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
        resultvar = 0
        pid = <value optimized out>
        selftid = 1237
#1  0x00007fb42260c125 in abort () at abort.c:92
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7fff9732fcc8, sa_sigaction = 0x7fff9732fcc8}, sa_mask = {__val = {140735730089136, 140735730118397, 15, 140411648777162, 1, 140411648780821, 3, 140735730089131, 5, 140411648777188, 
              1, 140411648783873, 3, 140735730089140, 12, 140411648783877}}, sa_flags = 2, sa_restorer = 0x7fb42272b605}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007fb42264782b in __libc_message (do_abort=2, fmt=0x7fb42272c7f8 "*** glibc detected *** %s: %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:186
        ap = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7fff97330630, reg_save_area = 0x7fff97330540}}
        ap_copy = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fff97330630, reg_save_area = 0x7fff97330540}}
        fd = 2
        on_2 = <value optimized out>
        list = <value optimized out>
        nlist = <value optimized out>
        cp = <value optimized out>
        written = <value optimized out>
#3  0x00007fb42264d156 in malloc_printerr (action=3, str=0x7fb42272caf0 "free(): invalid next size (fast)", ptr=<value optimized out>) at malloc.c:6283
        buf = "00007fb428754e80"
        cp = <value optimized out>
#4  0x00007fb419988a92 in htp_tx_destroy (tx=0x7fb428753240) at htp_transaction.c:143
        hl = 0x0
        h = 0x7fb428754e80
#5  0x00007fb416db5a74 in modhtp_htp_response (connp=<value optimized out>) at htp.c:693
        modctx = <value optimized out>
        tx = 0x7fb428753240
        ib = 0x7fb4254cb760
        itx = 0x7fb428753c70
#6  0x00007fb41997ef33 in hook_run_all (hook=0x7fb4287527d0, data=0x7fb42874ac10) at hooks.c:144
        callback = <value optimized out>
#7  0x00007fb41998775c in htp_connp_RES_IDLE (connp=0x7fb42874ac10) at htp_response.c:725
        rc = <value optimized out>
#8  0x00007fb419987229 in htp_connp_res_data (connp=0x7fb42874ac10, timestamp=<value optimized out>, data=<value optimized out>, len=<value optimized out>) at htp_response.c:872
        rc = <value optimized out>
#9  0x00007fb416db4fbb in modhtp_iface_data_out (pi=<value optimized out>, qcdata=0x7fff97330840) at htp.c:950
        ib = 0x7fb4254cb760
        iconn = <value optimized out>
        modctx = 0x7fb428752168
        htp = 0x7fb42874ac10
        rc = IB_OK
        tv = {tv_sec = 1318876855, tv_usec = 855987}
        ec = <value optimized out>
#10 0x00007fb419776677 in process_bucket (f=0x7fb4254f5ce8, b=0x7fb4287078b8) at mod_ironbee.c:225
        c = 0x7fb4254f53a8
        ctx = 0x7fb4254f5c90
        icdata = {ib = 0x7fb4254cb760, mp = 0x7fb42873aca4, conn = 0x7fb428751f10, dalloc = 216, dlen = 216, 
          data = 0x7fb42545fe89 "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /administrateur.php was not found on this server.</p>"...}
        bdata = 0x7fb42545fe89 "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /administrateur.php was not found on this server.</p>"...
        nbytes = 216
        rc = <value optimized out>
#11 0x00007fb41977671b in ironbee_output_filter (f=0x7fb4254f5ce8, bb=0x7fb428748af8) at mod_ironbee.c:709
        b = 0x7fb4287078b8
#12 0x00007fb4240d248b in ap_http_header_filter (f=0x7fb4287436f0, b=0x7fb428748af8) at /usr/src/debug/httpd-2.2.15/modules/http/http_filters.c:1292
---Type <return> to continue, or q <return> to quit---
        r = 0x7fb4287420e8
        c = 0x7fb4254f53a8
        clheader = <value optimized out>
        protocol = 0x7fb4240d9f82 "HTTP/1.1"
        e = <value optimized out>
        b2 = <value optimized out>
        h = {pool = 0x7fb428742068, bb = 0x7fb428756520}
        ctx = <value optimized out>
        ctype = <value optimized out>
        eb = <value optimized out>
#13 0x00007fb4240b6d90 in ap_content_length_filter (f=0x7fb4287436c8, b=0x7fb428748af8) at /usr/src/debug/httpd-2.2.15/server/protocol.c:1335
        r = 0x7fb4287420e8
        ctx = 0x7fb428756490
        e = <value optimized out>
        eos = <value optimized out>
        eblock = <value optimized out>
#14 0x00007fb4240d41a1 in ap_byterange_filter (f=0x7fb4287436a0, bb=0x7fb428748af8) at /usr/src/debug/httpd-2.2.15/modules/http/byterange_filter.c:296
        r = 0x7fb4287420e8
        c = 0x7fb4254f53a8
        e = <value optimized out>
        bsend = <value optimized out>
        tmpbb = <value optimized out>
        range_start = <value optimized out>
        range_end = <value optimized out>
        clength = <value optimized out>
        rv = <value optimized out>
        found = 0
        num_ranges = 32692
        boundary = 0x0
        bound_head = 0x0
        indexes = <value optimized out>
        idx = <value optimized out>
        original_status = 404
        i = <value optimized out>
#15 0x00007fb41a9bf9b9 in ap_proxy_http_process_response (p=0x7fb428742068, r=<value optimized out>, backend=0x7fb425459d58, origin=0x7fb42545bf78, conf=0x7fb4254812e0, server_portstr=0x7fff97334e20 ":8080")
    at /usr/src/debug/httpd-2.2.15/modules/proxy/mod_proxy_http.c:1824
        readbytes = 216
        rv = <value optimized out>
        mode = APR_NONBLOCK_READ
        finish = <value optimized out>
        rc = <value optimized out>
        c = 0x7fb4254f53a8
        buffer = "\000\nntent-Type\000 text/html; charset=iso-8859-1\000\n PHP/5.3.2-1ubuntu4.5 with Suhosin-Patch mod_python/3.3.1 Python/2.6.5 mod_perl/2.0.4 Perl/v5.10.1\000\nMon Oct 17 13:40:55 2011] [debug] proxy_util.c(1506): ["...
        buf = <value optimized out>
        keepchar = <value optimized out>
        rp = 0x7fb428748b18
        e = <value optimized out>
        bb = 0x7fb428748ad8
        tmp_bb = 0x7fb4287559a8
        pass_bb = 0x7fb428748af8
        len = 22
        backasswards = <value optimized out>
        interim_response = 0
        pread_len = <value optimized out>
        save_table = <value optimized out>
---Type <return> to continue, or q <return> to quit---
        backend_broke = 0
        hop_by_hop_hdrs = {0x7fb41a9c25e1 "Keep-Alive", 0x7fb41a9c2959 "Proxy-Authenticate", 0x7fb41a9c2837 "TE", 0x7fb41a9c283a "Trailer", 0x7fb41a9c2842 "Upgrade", 0x0}
        i = <value optimized out>
        te = 0x0
        original_status = 200
        proxy_status = 404
        original_status_line = 0x0
        proxy_status_line = <value optimized out>
#16 0x00007fb41a9c0df7 in proxy_http_handler (r=0x7fb4287420e8, worker=<value optimized out>, conf=0x7fff97334e08, url=0x7fb428748400 "/administrateur.php", proxyname=0x7fb4254ff188 "(1O%\264\177", proxyport=49016)
    at /usr/src/debug/httpd-2.2.15/modules/proxy/mod_proxy_http.c:2025
        status = <value optimized out>
        server_portstr = ":8080\000\000\000\020O3\227\377\177\000\000@N3\227\377\177\000\000\345\377\375\032\264\177\000"
        scheme = <value optimized out>
        proxy_function = 0x7fb41a9c275e "HTTP"
        u = <value optimized out>
        backend = 0x7fb425459d58
        is_ssl = 678724632
        c = 0x7fb4254f53a8
        p = 0x7fb428742068
        uri = <value optimized out>
#17 0x00007fb41afd8f6a in proxy_run_scheme_handler (r=0x7fb4287420e8, worker=0x7fb4254814b8, conf=0x7fb4254812e0, url=0x7fb4287482de "http://192.168.4.101/administrateur.php", proxyhost=0x0, proxyport=0)
    at /usr/src/debug/httpd-2.2.15/modules/proxy/mod_proxy.c:2380
        pHook = <value optimized out>
        n = <value optimized out>
        rv = <value optimized out>
#18 0x00007fb41afdd525 in proxy_handler (r=0x7fb4287420e8) at /usr/src/debug/httpd-2.2.15/modules/proxy/mod_proxy.c:996
        url = 0x7fb4287482de "http://192.168.4.101/administrateur.php"
        uri = 0x7fb4287482de "http://192.168.4.101/administrateur.php"
        scheme = 0x7fb428748308 "http"
        p = 0x7fff97334f88 "k\351\t0[\200\275\027ނt(\264\177"
        p2 = <value optimized out>
        sconf = <value optimized out>
        conf = 0x7fb4254812e0
        proxies = 0x7fb4254813b0
        ents = 0x7fb4253ad830
        i = <value optimized out>
        access_status = 0
        direct_connect = <value optimized out>
        str = <value optimized out>
        maxfwd = <value optimized out>
        balancer = 0x0
        worker = 0x7fb4254814b8
        attempts = 0
        max_attempts = 0
        list = <value optimized out>
#19 0x00007fb4240c28c0 in ap_run_handler (r=0x7fb4287420e8) at /usr/src/debug/httpd-2.2.15/server/config.c:158
        pHook = <value optimized out>
        n = <value optimized out>
        rv = <value optimized out>
#20 0x00007fb4240c617e in ap_invoke_handler (r=0x7fb4287420e8) at /usr/src/debug/httpd-2.2.15/server/config.c:376
        handler = <value optimized out>
        p = <value optimized out>
        result = 0
        old_handler = 0x7fb41afe43fe "proxy-server"
        ignore = <value optimized out>
#21 0x00007fb4240d17e0 in ap_process_request (r=0x7fb4287420e8) at /usr/src/debug/httpd-2.2.15/modules/http/http_request.c:282
---Type <return> to continue, or q <return> to quit---
        access_status = <value optimized out>
#22 0x00007fb4240ce6a8 in ap_process_http_connection (c=0x7fb4254f53a8) at /usr/src/debug/httpd-2.2.15/modules/http/http_core.c:190
        r = 0x7fb4287420e8
        csd = 0x0
#23 0x00007fb4240ca3d8 in ap_run_process_connection (c=0x7fb4254f53a8) at /usr/src/debug/httpd-2.2.15/server/connection.c:43
        pHook = <value optimized out>
        n = <value optimized out>
        rv = <value optimized out>
#24 0x00007fb4240d66f7 in child_main (child_num_arg=<value optimized out>) at /usr/src/debug/httpd-2.2.15/server/mpm/prefork/prefork.c:667
        current_conn = <value optimized out>
        csd = 0x7fb4254f51b8
        ptrans = 0x7fb4254f5138
        allocator = 0x7fb4254f3030
        status = <value optimized out>
        i = <value optimized out>
        lr = <value optimized out>
        pollset = 0x7fb4254f3358
        sbh = 0x7fb4254f3350
        bucket_alloc = 0x7fb4254ff188
        last_poll_idx = 1
#25 0x00007fb4240d6a0a in make_child (s=0x7fb425347860, slot=4) at /usr/src/debug/httpd-2.2.15/server/mpm/prefork/prefork.c:763
        pid = 0
#26 0x00007fb4240d6d3b in startup_children (_pconf=<value optimized out>, plog=<value optimized out>, s=<value optimized out>) at /usr/src/debug/httpd-2.2.15/server/mpm/prefork/prefork.c:781
        i = <value optimized out>
#27 ap_mpm_run (_pconf=<value optimized out>, plog=<value optimized out>, s=<value optimized out>) at /usr/src/debug/httpd-2.2.15/server/mpm/prefork/prefork.c:1002
        index = <value optimized out>
        remaining_children_to_start = <value optimized out>
        rv = <value optimized out>
#28 0x00007fb4240ae840 in main (argc=1, argv=0x7fff973354e8) at /usr/src/debug/httpd-2.2.15/server/main.c:740
        c = 0 '\000'
        configtestonly = <value optimized out>
        confname = 0x7fb4240d8f44 "conf/httpd.conf"
        def_server_root = 0x7fb4240d8f39 "/etc/httpd"
        temp_error_log = 0x0
        error = <value optimized out>
        process = 0x7fb425347860
        server_conf = 0x7fb425347860
        pglobal = 0x7fb42533e128
        pconf = 0x7fb425340138
        plog = 0x7fb4253722c8
        ptemp = 0x7fb425344158
        pcommands = 0x7fb425342148
        opt = 0x7fb425342240
        rv = <value optimized out>
        mod = <value optimized out>
        optarg = 0x7fb42533a250 ""
        signal_server = <value optimized out>
```

**Comment by ivanr** [comment]
IIRC, this ended up not being a libhtp issue.
